apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::213652672693:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-WTVR55YVDWWN
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::213652672693:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-01T00:47:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "7690"
  uid: 3698a30d-3964-432b-8eb2-8b7918d59115
